default: &default
  adapter: mysql2
  encoding: utf8mb4
  reconnect: true
  pool: 32
  username: waikiki
  password: dhkdlzlzlfh!!
  host: 52.78.1.14
  database: waikiki_development

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3

spec:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3

development:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
  database: waikiki_production
