default: &default
  adapter: mysql2
  encoding: utf8mb4
  reconnect: true
  pool: 32
  host: metabot.tk
  database: waikiki_development
  username: waikiki
  password: dhkdlzlzlfh!!

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3

spec:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3

development:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
  host: kiki.video
  database: waikiki_production
  username: waikiki
  password: asjkgF,_ls12n#T
