:pidfile: ./shared/pids/sidekiq.pid
:daemon: true

staging:
  :verbose: true
  :logfile: ./shared/log/sidekiq.staging.log
  :concurrency: 5
  :timeout: 30
  :queues:
    - default

production:
  :verbose: false
  :logfile: ./shared/log/sidekiq.production.log
  :concurrency: 20
  :timeout: 3
  :queues:
    - default